apiVersion: v1
kind: ConfigMap
metadata:
  name: bind
  namespace: remediation
data:
  named.conf.options: |
    options {
            directory "/var/cache/bind";
            dnssec-validation no;
            allow-query { any; };
         
    };
  
