apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredns
  namespace: remediation
  labels:
    app: coredns
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: coredns
  template:
    metadata:
      labels:
        app: coredns
    spec:
      containers:
      - name: coredns
        image: coredns/coredns
        args: [ "-conf", "/etc/coredns/Corefile" ]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/coredns/Corefile
          subPath: Corefile
        - name: cert
          mountPath: /etc/coredns/cert.pem
          subPath: cert.pem
        - name: ca
          mountPath: /etc/coredns/ca.pem
          subPath: ca.pem
        - name: key
          mountPath: /etc/coredns/key.pem
          subPath: key.pem         
        ports:
        - containerPort: 53
          name: dns-udp
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        - containerPort: 853
          name: dns-over-tls
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - all
          readOnlyRootFilesystem: true
      volumes:
        - name: config-volume
          configMap:
            name: coredns	
        - name: cert
          configMap:
            name: cert
        - name: ca
          configMap:
            name: ca
        - name: key
          configMap:
            name: key
