apiVersion: v1
kind: Service
metadata:
  name: coredns
  namespace: remediation
  labels:
    app: coredns
spec:
  selector:
    app: coredns 
  ports:
  - name: dns-udp
    targetPort: 53
    port: 53
    protocol: UDP
  - name: dns-tcp
    targetPort: 53
    port: 53
    protocol: TCP
  - name: dns-over-tls
    targetPort: 853
    port: 853
    protocol: TCP
    
