apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: remediation
data:
  Corefile: |
    .:53 {
        forward . 192.168.254.191:53
        errors
        log
        
    }
    tls://.:853 {
        tls /etc/coredns/cert.pem /etc/coredns/key.pem /etc/coredns/ca.pem
        forward . 192.168.254.191:53
        errors
        log
    }
