apiVersion: v1
kind: Pod
metadata:
  name: netshoot
  namespace: remediation
spec:
  containers:
  - name: netshoot
    image: nicolaka/netshoot
    command: ["/bin/bash"]
    args: ["-c", "tail -f /dev/null"]
